### ISSUE TITLE
Feature Request: Team File Listing

### ISSUE THREAD

**Issue by ylluminate** [Amonith/mattermost-file-list#13]
Could you please extend this to also facilitate showing all files that are part of a team? 

Obviously admins would see all files and non-admins would see files that they have permission to access, but this would be very helpful in finding things quickly that have been uploaded.

**Comment by Amonith** [comment]
Hi,

Sure, can do.
I've started working on it on a separate branch. Based on my availability I think it should be done in a week or so, but we'll see about that.

**Comment by Amonith** [comment]
I'm thinking whether I should allow searching for files of channels where the admin is not a member. I mean, by default an admin can't even see a list of private channels, let alone browser their contents.
I'll probably add an opt-in config setting for this feature because it seems weird from privacy standpoint.

Now that I think of it, Mattermost might even block downloading of files from channels where one is not a member, but I'll just display file names instead of links if need be.

**Comment by ylluminate** [comment]
Well, yeah, I think this approach of flexibility is good.  Better to give such options to admin users vs locking them down.

**Comment by Amonith** [comment]
@ylluminate 
The feature is ready. Check it out in the latest release:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.7.0

**Comment by ylluminate** [comment]
Thanks so much! I'm curious about something: I'm not seeing this in my "Plugin Marketplace" and thus I'm not seeing an update feature there either.  Apparently it is showing up as a "LOCAL" install...  Is there a way to make this via the Marketplace and thus offer an update feature vs manually updating it?

**Comment by ylluminate** [comment]
Also, you have "enable" repeated on the settings :) : `For admins enable enable a list of all files in the team, even from channels where the admin is not a member`

**Comment by ylluminate** [comment]
Also, I think a tab at the top could be helpful for admins: "Channel" & "Team" 

Right now it appears that all team attachments are being showed within the "Channel" and thus this is confusing.  Basically it could be "Files for" <render buttons/tabs> [channel | team]

Does that make sense?

**Comment by Amonith** [comment]
> ... I'm not seeing this in my "Plugin Marketplace" and thus I'm not seeing an update feature there either. Apparently it is showing up as a "LOCAL" install... Is there a way to make this via the Marketplace and thus offer an update feature vs manually updating it?

As far as I know this is not yet possible. Mattermost team manages the marketplace manually. This will probably change in the future:

https://docs.mattermost.com/administration/plugins.html#mattermost-marketplace


> Also, you have "enable" repeated on the settings :) : For admins enable enable a list of all files in the team, even from channels where the admin is not a member.

Thanks, will be fixed in the next release :D

> Right now it appears that all team attachments are being showed within the "Channel" and thus this is confusing. Basically it could be "Files for" <render buttons/tabs> [channel | team]

I get the second part. I don't quite like the second button above the channel list either :D Probably will move it somewhere else in the future releases.
Not sure what you mean that "it appears that all team attachments are being showed within the "Channel"". Currently the button in the top bar opens the list of files in the channel (as the modal title suggests) and the button above the channel list opens list of files in the entire team (that's why I also added a new "Channel" column to the table.
