### ISSUE TITLE
error upload plugin 

### ISSUE THREAD

**Issue by NexusEFR** [Amonith/mattermost-file-list#35]
Hello, fantastic project for mattermost, but I have a problem, my platform is mattermost via Qnap NAS server and I understand that installed under Qnap QTS system on your embedded Linux. All plugins can be installed via console without problem or through their market place but your plugin gives the following error. I'm not a programmer, just a system user, could anything be done to make the installation work? 

An error was encountered when extracting the plugin. Review the contents of the plugin file and try again.

Thanks a lot!

**Comment by Amonith** [comment]
Hi, thanks for the kind words :)
I saw this kind of error one time when Mattermost process did not have permissions to extract the plugin archive to the plugins directory. For me it happened because during upgrading MM and moving folders I broke ownership settings for those folders.

You may want to check that, not sure how to help further. It's interesting that only my plugin doesn't work though. Should be a pretty normal .tar.gz archive.
If all fails you can also try to extract it manually to the plugin folder, maybe then you will receive some more detailed messages from the system itself.

**Comment by bbodenmiller** [comment]
Someone else found file size can be an issue: https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/101#issuecomment-643446448

**Comment by mksondej** [comment]
Great find @bbodenmiller!
I added info about this to the troubleshooting section in the README and I'll close this issue for now.
